name: TPC-H Benchmark (with collector)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: gpu

    steps:
      - uses: actions/checkout@v2

      - name: Check User
        run: whoami

      - name: Check Path
        run: pwd

      - name: Check Access to VE
        run: /opt/nec/ve/bin/vecmd info

      - name: Branch Ref
        run: echo ${GITHUB_REF#refs/heads/}

      - name: Run TPC-H@1
        run: sbt tpcbench-run/run
        if: success()

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"

      - name: Copying to sparkcyclone.io
        if: always()
        run: rsync -r -v tpcbench-run/target/tpc-html/ egonzalez@xpressai.jp:/var/www/sparkcyclone.io/tpc-html/b-${{ steps.date.outputs.date }}

