name: TPC-H Benchmark (with collector)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: gpu

    steps:
      - uses: actions/checkout@v2
      
      - name: Check User
        run: whoami
        
      - name: Check Path
        run: pwd
        
      - name: Check Access to VE
        run: /opt/nec/ve/bin/vecmd info

      - name: Branch Ref
        run: echo ${GITHUB_REF#refs/heads/}

      - name: Run TPC-H@1
        run: sbt tpcbench-run/reStart
        if: success()

