name: TPC-H Benchmark (with collector)

on:
  workflow_dispatch:
    inputs:
      scale:
        type: choice
        description: Scale to run
        options:
          - 1
          - 10
          - 20
      query:
        type: choice
        description: Query to run
        options:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
          - 13
          - 14
          - 15
          - 16
          - 17
          - 18
          - 19
          - 20
          - 21
          - 22
          - all

jobs:
  build:
    runs-on: gpu

    steps:
      - uses: actions/checkout@v2

      - name: Check User
        run: whoami

      - name: Check Path
        run: pwd

      - name: Check Access to VE
        run: /opt/nec/ve/bin/vecmd info

      - name: Branch Ref
        run: echo ${GITHUB_REF#refs/heads/}

      - name: Run TPC-H@1
        run: sbt "tpcbench-run/run --query=${{ github.event.inputs.query }} --scale=${{ github.event.inputs.scale }}"
        if: success()

      - name: Copying to sparkcyclone.io
        if: always()
        run: rsync -r -v tpcbench-run/target/tpc-html/ egonzalez@xpressai.jp:/var/www/sparkcyclone.io/tpc-html/summary

