---
name: "TPC-H Benchmark (with collector)"
env:
  INPUT_cyclone: "${{ github.event.inputs.cyclone }}"
  INPUT_extra: "${{ github.event.inputs.extra }}"
  INPUT_query: "${{ github.event.inputs.query }}"
  INPUT_scale: "${{ github.event.inputs.scale }}"
  INPUT_serializer: "${{ github.event.inputs.serializer }}"
  INPUT_ve-log-debug: "${{ github.event.inputs.ve-log-debug }}"
"on":
  workflow_dispatch:
    inputs:
      cyclone:
        type: "boolean"
        required: true
        description: "Use cyclone"
        default: "true"
      extra:
        type: "input"
        required: true
        description: "Extra command line arguments to add to Spark"
      query:
        type: "choice"
        required: true
        description: "Query to use"
        options:
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"
        - "6"
        - "7"
        - "8"
        - "9"
        - "10"
        - "11"
        - "12"
        - "13"
        - "14"
        - "15"
        - "16"
        - "17"
        - "18"
        - "19"
        - "20"
        - "21"
        - "22"
        - "all"
        default: "1"
      scale:
        type: "choice"
        required: true
        description: "Scale"
        options:
        - "1"
        - "10"
        - "20"
        default: "1"
      serializer:
        type: "boolean"
        required: true
        description: "Use Serializer"
        default: "true"
      ve-log-debug:
        type: "boolean"
        required: true
        description: "Debug VE logs"
        default: "false"
jobs:
  build:
    runs-on: "gpu"
    steps:
    - uses: "actions/checkout@v2"
    - name: "Check User"
      run: "whoami"
    - name: "Check Path"
      run: "pwd"
    - name: "Check Access to VE"
      run: "/opt/nec/ve/bin/vecmd info"
    - name: "Branch Ref"
      run: "echo ${GITHUB_REF#refs/heads/}"
    - name: "Run TPC-H@1"
      run: "sbt tpcbench-run/run"
      if: "success()"
    - name: "Copying to sparkcyclone.io"
      if: "always()"
      run: "rsync -r -v tpcbench-run/target/tpc-html/ egonzalez@xpressai.jp:/var/www/sparkcyclone.io/tpc-html/summary"
