name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      
      - name: Check User
        run: who am i
        
      - name: Check Path
        run: pwd

      - name: Branch Ref
        run: echo ${GITHUB_REF#refs/heads/}

      - name: Run Vector Engine Tests
        run: sbt "VectorEngine / test"
