name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Branch Ref
        run: echo ${GITHUB_REF#refs/heads/}

      - name: Run Vector Engine Tests
        run: sbt "VectorEngine / test"
