name: Unit tests (CMake)

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
      - ready_for_review

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Coursier cache
        uses: coursier/cache-action@v6
      - name: Install G++ 11
        run: |
          sudo apt-get -y install g++-11
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 110 --slave /usr/bin/g++ g++ /usr/bin/g++-11 --slave /usr/bin/gcov gcov /usr/bin/gcov-11
          g++ -v
          gcc -v
      - uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: temurin
      - name: Generate TPC-H Data
        run: pushd src/test/resources/dbgen/ && make && ./dbgen && popd
      - name: Run CMake Tests
        run: sbt "CMake / testQuick"
